services:
  - type: web
    name: quizmaster
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
